### ISSUE TITLE
interesting additions

### ISSUE THREAD

**Issue by ianbed** [vari-bbc/rnaseq_workflow#15]
Would be nice to print the GO.XX tables that go into the clusterprofiler functions.
Would also be nice to toggle enrichment between up/down genes.
just some thoughts

**Comment by genomics-kl** [comment]
Just speaking from the point of view of implementing these via bbcRNA in general not in the pipeline specifically...

1. The tables can be extracted via the following:

```
bbc_obj_DEN_gsea_kegg <- run_gsea(bbc_obj_DEN, 
                                      gene_set="kegg", 
                                      organism="mmu", 
                                      orgDb="org.Mm.eg.db")

gsea_names <- names(bbc_obj_DEN_gsea_kegg)

out <- lapply(gsea_names, function(x){
  readr::write_tsv(as.data.frame(bbc_obj_DEN_gsea_kegg[[x]]), 
                   paste0("./out_files/", x, "_kegg_gsea.tsv"))})
```
2. Not sure if this is what you were asking but I recently added options to do GSEA or hypergeometric tests with or without considering up vs down regulated genes.

```
# hypergeometric, splitting by LFC direction
run_hypergeometric(x, de_pkg = "edger", split_by_lfc_dir = TRUE)

# hypergeometric, don't split
run_hypergeometric(x, de_pkg = "edger", split_by_lfc_dir = FALSE)
```

```
# GSEA, ranked by signed -log10pval
run_gsea(x, de_pkg = "edger", rank_by = "signed-log10pval")

# GSEA, ranked by -log10pval
run_gsea(x, de_pkg = "edger", rank_by = "-log10pval")
```

**Comment by deanpettinga** [comment]
looks like Kin has addressed this issue. not sure it falls under the purview of this workflow, but rather the bbcRNA package.
