### ISSUE TITLE
Deprecate clusters.yaml

### ISSUE THREAD

**Issue by genomics-kl** [vari-bbc/rnaseq_workflow#17]
Specify memory and threads in the rules themselves. This is easier to read and makes it more convenient to add new rules.

**Comment by deanpettinga** [comment]
I'm gunna assign this to myself unless you'd like to do it, @genomics-kl.

**Comment by genomics-kl** [comment]
Yep, that would be great. Thanks in advance, @deanpettinga !

**Comment by deanpettinga** [comment]
addressed by 347ba93dcc6a8b30a07bf0cf16ff603590680336.
